evaluation:
  context: "A client called and said: I am not sure I will be free on Friday. Tuesday is a good day, but still worse than Friday. But probably Tuesday is better than Wednesday. Although I am also busy on Wednesday."
  question: "On which day is the patient free?"
  expected_answer: "Tuesday"
  
judge:
  model: "llama3.2:3b"
  total_requests: 1000

output:
  show_progress: true
  show_all_scores: false